#!/bin/sh

# Mount the proc filesystem
mkdir /proc
mount -t proc proc /proc

# Insert any kernel modules
find /lib/modules -type f -exec insmod {} \;

# Mount the squashfs as read only
mkdir -p /mnt/ro
mount -o loop -t squashfs /rootfs.sfs /mnt/ro

# Mount a tmpfs for write capibilities
mkdir -p /mnt/rw
MEMSIZE=$(awk '/^MemTotal:/ { print $2 }' /proc/meminfo)
mount -t tmpfs -o size=${MEMSIZE}k,mode=0755 tmpfs /mnt/rw

# Use an aufs layer to redirect changes from the rootfs to the tmpfs
# Use the result as the root we will switch to
mount -t aufs -o dirs=/mnt/rw=rw:/mnt/ro=ro aufs /root

# Make the initramfs mount points available in the root
mkdir -p /root/mnt/ro
mkdir -p /root/mnt/rw

mount --bind /mnt/ro /root/mnt/ro
mount --bind /mnt/rw /root/mnt/rw

# Install busybox into the system
cp /bin/busybox /root/bin/busybox
busybox --install -s /root/bin

# Boot into rootfs
umount /proc
exec switch_root -c /dev/console /root /sbin/init

